export const nodeTypes = [
	// Primary Scans
	{
		field: 'Seq Scan',
		description:
			'Scans the entire table page-by-page (in 8KB chunks). Efficient for small tables, but can be I/O intensive for large tables due to the amount of data reviewed.',
		subValues: {
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Relation Name': 'nodes',
			Schema: 'public',
			Alias: 'nodes',
			'Startup Cost': 0,
			'Total Cost': 189,
			'Plan Rows': 9999,
			'Plan Width': 22,
			'Actual Startup Time': 0.096,
			'Actual Total Time': 0.097,
			'Actual Rows': 1,
			'Actual Loops': 1,
			Output: ['id', 'random'],
			Filter: '(nodes.id > 1)',
			'Rows Removed by Filter': 1,
			'Shared Hit Blocks': 2,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Index Only Scan',
		description:
			'Fetches data directly from the index pages without touching the table heap. Generally the fastest scan type because indexes are more compact.',
		subValues: {
			'Node Type': 'Index Only Scan',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Scan Direction': 'Forward',
			'Index Name': 'some_index',
			'Relation Name': 'nodes',
			Schema: 'public',
			Alias: 'nodes',
			'Startup Cost': 0.29,
			'Total Cost': 1.4,
			'Plan Rows': 1,
			'Plan Width': 4,
			'Actual Startup Time': 0.027,
			'Actual Total Time': 0.027,
			'Actual Rows': 1,
			'Actual Loops': 1,
			Output: ['id'],
			'Index Cond': '(nodes.id = 1)',
			'Rows Removed by Index Recheck': 0,
			'Heap Fetches': 0,
			'Shared Hit Blocks': 3,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Index Scan',
		description:
			'Uses an index to find specific row locations and then fetches only the necessary pages from the table. Best for filtering uncommon values.',
		subValues: {
			'Node Type': 'Index Scan',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Scan Direction': 'Forward',
			'Index Name': 'some_index',
			'Relation Name': 'nodes',
			Schema: 'public',
			Alias: 'nodes',
			'Startup Cost': 0.29,
			'Total Cost': 2.5,
			'Plan Rows': 1,
			'Plan Width': 22,
			'Actual Startup Time': 0.033,
			'Actual Total Time': 0.033,
			'Actual Rows': 1,
			'Actual Loops': 1,
			Output: ['id', 'random'],
			'Index Cond': '(nodes.id = 1)',
			'Rows Removed by Index Recheck': 0,
			'Shared Hit Blocks': 1,
			'Shared Read Blocks': 2,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	// Bit Scans
	{
		field: 'Bitmap Index Scan',
		description:
			'Uncovers relevant pages from an index and populates an in-memory bitmap (list of 1s and 0s where a 1 means check the page) to allow for sequential-like table access.',
		subValues: {
			'Node Type': 'Bitmap Index Scan',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Index Name': 'some_index',
			'Startup Cost': 0,
			'Total Cost': 1.39,
			'Plan Rows': 1,
			'Plan Width': 0,
			'Actual Startup Time': 0.005,
			'Actual Total Time': 0.005,
			'Actual Rows': 1,
			'Actual Loops': 1,
			'Index Cond': '(nodes.id = 1)',
			'Shared Hit Blocks': 2,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'BitmapAnd',
		description:
			'Combines multiple bitmaps from independent indexes using boolean AND logic before performing a table scan.',
		subValues: {
			'Node Type': 'BitmapAnd',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 445.63,
			'Total Cost': 445.63,
			'Plan Rows': 4041,
			'Plan Width': 0,
			'Actual Startup Time': 9.704,
			'Actual Total Time': 9.705,
			'Actual Rows': 0,
			'Actual Loops': 1,
			'Shared Hit Blocks': 0,
			'Shared Read Blocks': 39,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'BitmapOr',
		description:
			'Combines multiple bitmaps from independent indexes using boolean OR logic before performing a table scan.',
		subValues: {
			'Node Type': 'BitmapOr',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 461.44,
			'Total Cost': 461.44,
			'Plan Rows': 40207,
			'Plan Width': 0,
			'Actual Startup Time': 1.385,
			'Actual Total Time': 1.387,
			'Actual Rows': 0,
			'Actual Loops': 1,
			'Shared Hit Blocks': 39,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Bitmap Heap Scan',
		description:
			'The final stage of a bit scan where the combined bitmap is used to fetch the actual data rows from the table heap.',
		subValues: {
			'Node Type': 'Bitmap Heap Scan',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Relation Name': 'nodes',
			Schema: 'public',
			Alias: 'nodes',
			'Startup Cost': 1.39,
			'Total Cost': 2.51,
			'Plan Rows': 1,
			'Plan Width': 4,
			'Actual Startup Time': 0.018,
			'Actual Total Time': 0.018,
			'Actual Rows': 1,
			'Actual Loops': 1,
			Output: ['id'],
			'Recheck Cond': '(nodes.id = 1)',
			'Rows Removed by Index Recheck': 0,
			'Exact Heap Blocks': 1,
			'Lossy Heap Blocks': 0,
			'Shared Hit Blocks': 3,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	// Join Algorithms
	{
		field: 'Nested Loop',
		description:
			'Compares every row of one table against every row of another. Can be CPU intensive; typically preferred when at least one of the joined tables are small.',
		subValues: {
			'Node Type': 'Nested Loop',
			'Parallel Aware': false,
			'Async Capable': false,
			'Join Type': 'Inner',
			'Startup Cost': 0.42,
			'Total Cost': 7738.2,
			'Plan Rows': 10265,
			'Plan Width': 4,
			'Actual Startup Time': 6.296,
			'Actual Total Time': 122.505,
			'Actual Rows': 20000,
			'Actual Loops': 1,
			Output: ['nodes.id'],
			'Inner Unique': false,
			'Shared Hit Blocks': 30065,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Hash Join',
		description:
			'Builds a hash table of join keys from one table to allow O(N) lookups against the second table. Performant but has memory overhead.',
		subValues: {
			'Node Type': 'Hash Join',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Join Type': 'Inner',
			'Startup Cost': 289,
			'Total Cost': 14957.5,
			'Plan Rows': 6038,
			'Plan Width': 4,
			'Actual Startup Time': 4.343,
			'Actual Total Time': 1600.355,
			'Actual Rows': 10000,
			'Actual Loops': 2,
			Output: ['nodes.id'],
			'Inner Unique': false,
			'Hash Cond': '(nodes.id = join_node.id)',
			'Shared Hit Blocks': 6646,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Workers: [
				{
					'Worker Number': 0,
					'Actual Startup Time': 4.498,
					'Actual Total Time': 1592.558,
					'Actual Rows': 8780,
					'Actual Loops': 1,
					'Shared Hit Blocks': 3319,
					'Shared Read Blocks': 0,
					'Shared Dirtied Blocks': 0,
					'Shared Written Blocks': 0,
					'Local Hit Blocks': 0,
					'Local Read Blocks': 0,
					'Local Dirtied Blocks': 0,
					'Local Written Blocks': 0,
					'Temp Read Blocks': 0,
					'Temp Written Blocks': 0,
					'WAL Records': 0,
					'WAL FPI': 0,
					'WAL Bytes': 0
				}
			],
			Plans: []
		}
	},
	{
		field: 'Merge Join',
		description:
			"Joins two tables by 'walking' through them simultaneously. Requires both tables to be pre-sorted on the join columns.",
		subValues: {
			'Node Type': 'Merge Join',
			'Parallel Aware': false,
			'Async Capable': false,
			'Join Type': 'Inner',
			'Startup Cost': 828.94,
			'Total Cost': 1331.79,
			'Plan Rows': 10265,
			'Plan Width': 4,
			'Actual Startup Time': 24.18,
			'Actual Total Time': 47.809,
			'Actual Rows': 20000,
			'Actual Loops': 1,
			Output: ['nodes.id'],
			'Inner Unique': false,
			'Merge Cond': '(nodes.id = join_node.id)',
			'Shared Hit Blocks': 122,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	// Parallel / Gather
	{
		field: 'Gather',
		description:
			'Combines results from multiple parallel workers into a single output without preserving the sort order.',
		subValues: {
			'Node Type': 'Gather',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 1289,
			'Total Cost': 16984,
			'Plan Rows': 10265,
			'Plan Width': 4,
			'Actual Startup Time': 5.475,
			'Actual Total Time': 1405.966,
			'Actual Rows': 20000,
			'Actual Loops': 1,
			Output: ['nodes.id'],
			'Workers Planned': 1,
			'Workers Launched': 1,
			'Single Copy': false,
			'Shared Hit Blocks': 6646,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Gather Merge',
		description:
			'Combines results from multiple parallel workers while preserving the original sort order of the data.',
		subValues: {
			'Node Type': 'Gather Merge',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 83199.57,
			'Total Cost': 150846.6,
			'Plan Rows': 588235,
			'Plan Width': 41,
			'Actual Startup Time': 321.992,
			'Actual Total Time': 558.218,
			'Actual Rows': 1000000,
			'Actual Loops': 1,
			Output: ['id', 'val', 'payload'],
			'Workers Planned': 1,
			'Workers Launched': 1,
			'Shared Hit Blocks': 9382,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 12490,
			'Temp Written Blocks': 12514,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	// Aggregate / Grouping
	{
		field: 'Aggregate',
		description:
			'Executes an aggregation function (like SUM or COUNT) against a set of values, maintaining a running state.',
		subValues: {
			'Node Type': 'Aggregate',
			Strategy: 'Plain',
			'Partial Mode': 'Finalize',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 16002.28,
			'Total Cost': 16002.29,
			'Plan Rows': 1,
			'Plan Width': 8,
			'Actual Startup Time': 1011.293,
			'Actual Total Time': 1015.895,
			'Actual Rows': 1,
			'Actual Loops': 1,
			Output: ['count(*)'],
			'Shared Hit Blocks': 2401,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'HashAggregate',
		description:
			'Uses an in-memory hash table to group rows (GROUP BY OR DISTINCT) for aggregation. Fast for non-sorted data as it avoids the overhead of a full sort.'
	},
	{
		field: 'GroupAggregate',
		description:
			'Aggregates data that has been sorted by the group key instead of hashed. More efficient for large datasets as sorted rows can be spilled to disk.'
	},
	{
		field: 'Group',
		description:
			"Removes duplicate values from a scan node based on a GROUP BY clause when an aggregate function isn't present.",
		subValues: {
			'Node Type': 'Group',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 0.42,
			'Total Cost': 13446.92,
			'Plan Rows': 500000,
			'Plan Width': 18,
			'Actual Startup Time': 3.589,
			'Actual Total Time': 1290.855,
			'Actual Rows': 500000,
			'Actual Loops': 1,
			Output: ['id', 'customer_id', 'amount'],
			'Group Key': ['sales.id'],
			'Shared Hit Blocks': 4554,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	// Processing & Caching
	{
		field: 'Sort',
		description:
			'Orders data in memory using quicksort or heapsort. May perform an external merge sort on disk for very large datasets.',
		subValues: {
			'Node Type': 'Sort',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 67526.92,
			'Total Cost': 68776.92,
			'Plan Rows': 500000,
			'Plan Width': 18,
			'Actual Startup Time': 219.263,
			'Actual Total Time': 275.183,
			'Actual Rows': 500000,
			'Actual Loops': 1,
			Output: ['id', 'customer_id', 'amount'],
			'Sort Key': ['sales.customer_id'],
			'Sort Method': 'external merge',
			'Sort Space Used': 14224,
			'Sort Space Type': 'Disk',
			'Shared Hit Blocks': 3188,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 3551,
			'Temp Written Blocks': 3565,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Incremental Sort',
		description:
			'Optimizes sorting by ordering only remaining columns when leading columns are already sorted by a previous operation or index.',
		subValues: {
			'Node Type': 'Incremental Sort',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 0.46,
			'Total Cost': 34696.92,
			'Plan Rows': 500000,
			'Plan Width': 18,
			'Actual Startup Time': 0.08,
			'Actual Total Time': 177.458,
			'Actual Rows': 500000,
			'Actual Loops': 1,
			Output: ['id', 'customer_id', 'amount'],
			'Sort Key': ['sales.id', 'sales.customer_id'],
			'Presorted Key': ['sales.id'],
			'Full-sort Groups': {
				'Group Count': 15625,
				'Sort Methods Used': ['quicksort'],
				'Sort Space Memory': {
					'Average Sort Space Used': 26,
					'Peak Sort Space Used': 26
				}
			},
			'Shared Hit Blocks': 4564,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Memoize',
		description:
			'Caches tuples from a scan as a hash to speed up repeated access, commonly used to optimize Nested Loop joins.'
	},
	{
		field: 'Materialize',
		description:
			'Caches the results of a child node in memory so the parent node can access the data more quickly without re-executing the child.',
		subValues: {
			'Node Type': 'CTE Scan',
			'Parallel Aware': false,
			'Async Capable': false,
			'CTE Name': 'my_cte',
			Alias: 'my_cte',
			'Startup Cost': 10,
			'Total Cost': 32.5,
			'Plan Rows': 333,
			'Plan Width': 4,
			'Actual Startup Time': 0.213,
			'Actual Total Time': 0.348,
			'Actual Rows': 500,
			'Actual Loops': 1,
			Output: ['my_cte.id'],
			Filter: '(my_cte.id > 500)',
			'Rows Removed by Filter': 500,
			'Shared Hit Blocks': 0,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Append',
		description: 'Combines sets produced by UNION operations. Does not preserve sort order',
		subValues: {
			'Node Type': 'Append',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 0,
			'Total Cost': 21803,
			'Plan Rows': 1020000,
			'Plan Width': 21,
			'Actual Startup Time': 0.045,
			'Actual Total Time': 191.493,
			'Actual Rows': 1020000,
			'Actual Loops': 1,
			'Shared Hit Blocks': 6503,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			'Subplans Removed': 0,
			Plans: []
		}
	},
	{
		field: 'Merge Append',
		description:
			"Combines sets produced by UNION operations. 'Merge' variation preserves the sort order between the sets.",
		subValues: {
			'Node Type': 'Merge Append',
			'Parent Relationship': 'Outer',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 828.86,
			'Total Cost': 80228.06,
			'Plan Rows': 1020000,
			'Plan Width': 36,
			'Actual Startup Time': 2.847,
			'Actual Total Time': 525.143,
			'Actual Rows': 1020000,
			'Actual Loops': 1,
			'Sort Key': ['nodes.id', 'nodes.random'],
			'Shared Hit Blocks': 29137,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			'Subplans Removed': 0,
			Plans: []
		}
	},
	// Specialized Scans
	{
		field: 'CTE Scan',
		description:
			'Fetches data from a temporary table defined in a WITH statement (Common Table Expression).',
		subValues: {
			'Node Type': 'CTE Scan',
			'Parallel Aware': false,
			'Async Capable': false,
			'CTE Name': 'my_cte',
			Alias: 'my_cte',
			'Startup Cost': 10,
			'Total Cost': 32.5,
			'Plan Rows': 333,
			'Plan Width': 4,
			'Actual Startup Time': 0.245,
			'Actual Total Time': 0.383,
			'Actual Rows': 500,
			'Actual Loops': 1,
			Output: ['my_cte.id'],
			Filter: '(my_cte.id > 500)',
			'Rows Removed by Filter': 500,
			'Shared Hit Blocks': 0,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Subquery Scan',
		description:
			'Fetches data from a complex subquery that the planner treats as a standalone table.',
		subValues: {
			'Node Type': 'Subquery Scan',
			'Parallel Aware': false,
			'Async Capable': false,
			Alias: 'sub',
			'Startup Cost': 0.29,
			'Total Cost': 191.34,
			'Plan Rows': 1250,
			'Plan Width': 21,
			'Actual Startup Time': 0.039,
			'Actual Total Time': 2.338,
			'Actual Rows': 1250,
			'Actual Loops': 1,
			Output: ['sub.id', 'sub.name', 'sub.region'],
			Filter: "(sub.region = 'EU'::text)",
			'Rows Removed by Filter': 3750,
			'Shared Hit Blocks': 52,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Function Scan',
		description:
			'Occurs when a database function (like generate_series) is referenced in the FROM clause as a data source.',
		subValues: {
			'Node Type': 'Function Scan',
			'Parent Relationship': 'InitPlan',
			'Subplan Name': 'CTE my_cte',
			'Parallel Aware': false,
			'Async Capable': false,
			'Function Name': 'generate_series',
			Schema: 'pg_catalog',
			Alias: 'id_1',
			'Startup Cost': 0,
			'Total Cost': 10,
			'Plan Rows': 1000,
			'Plan Width': 4,
			'Actual Startup Time': 0.09,
			'Actual Total Time': 0.157,
			'Actual Rows': 1000,
			'Actual Loops': 1,
			Output: ['id_1.id'],
			'Function Call': 'generate_series(1, 1000)',
			'Shared Hit Blocks': 0,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Tid Scan',
		description:
			'Fetches rows directly using their physical Current Tuple ID. Extremely fast but rarely used as CTIDs change over time.',
		subValues: {
			'Node Type': 'Tid Scan',
			'Parallel Aware': false,
			'Async Capable': false,
			'Relation Name': 'nodes',
			Schema: 'public',
			Alias: 'nodes',
			'Startup Cost': 0,
			'Total Cost': 1.11,
			'Plan Rows': 1,
			'Plan Width': 21,
			'Actual Startup Time': 1.172,
			'Actual Total Time': 1.173,
			'Actual Rows': 1,
			'Actual Loops': 1,
			Output: ['id', 'random'],
			'TID Cond': "(nodes.ctid = '(0,1)'::tid)",
			'Shared Hit Blocks': 1,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Tid Range Scan',
		description:
			'Fetches a range of rows directly using their physical Current Tuple ID. Extremely fast but rarely used as CTIDs change over time.',
		subValues: {
			'Node Type': 'Tid Range Scan',
			'Parallel Aware': false,
			'Async Capable': false,
			'Relation Name': 'nodes',
			Schema: 'public',
			Alias: 'nodes',
			'Startup Cost': 0.01,
			'Total Cost': 5.23,
			'Plan Rows': 313,
			'Plan Width': 21,
			'Actual Startup Time': 0.058,
			'Actual Total Time': 0.95,
			'Actual Rows': 312,
			'Actual Loops': 1,
			Output: ['id', 'random'],
			'TID Cond': "((nodes.ctid > '(0,1)'::tid) AND (nodes.ctid < '(2,1)'::tid))",
			'Shared Hit Blocks': 3,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Worktable Scan',
		description: 'Scans the temporary working table generated during a RECURSIVE query iteration.',
		subValues: {
			'Node Type': 'WorkTable Scan',
			'Parent Relationship': 'Inner',
			'Parallel Aware': false,
			'Async Capable': false,
			'CTE Name': 'nums',
			Alias: 'nums_1',
			'Startup Cost': 0,
			'Total Cost': 0.23,
			'Plan Rows': 3,
			'Plan Width': 4,
			'Actual Startup Time': 0,
			'Actual Total Time': 0,
			'Actual Rows': 1,
			'Actual Loops': 100,
			Output: ['(nums_1.n + 1)'],
			Filter: '(nums_1.n < 100)',
			'Rows Removed by Filter': 0,
			'Shared Hit Blocks': 0,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Values Scan',
		description: 'A scan performed on a constant list of values provided via the VALUES keyword.',
		subValues: {
			'Node Type': 'Values Scan',
			'Parallel Aware': false,
			'Async Capable': false,
			Alias: '*VALUES*',
			'Startup Cost': 0,
			'Total Cost': 0.04,
			'Plan Rows': 3,
			'Plan Width': 36,
			'Actual Startup Time': 0.012,
			'Actual Total Time': 0.013,
			'Actual Rows': 3,
			'Actual Loops': 1,
			Output: ['"*VALUES*".column1', '"*VALUES*".column2'],
			'Shared Hit Blocks': 0,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: []
		}
	},
	{
		field: 'Foreign / Custom Scan',
		description:
			'Scans data from external sources via a Foreign Data Wrapper or a non-native scan implemented by an extension.'
	}
];
