const duck = [
	{
		Plan: {
			'Node Type': 'Sort',
			'Parallel Aware': false,
			'Async Capable': false,
			'Startup Cost': 21.8,
			'Total Cost': 21.84,
			'Plan Rows': 16,
			'Plan Width': 277,
			'Actual Startup Time': 2.446,
			'Actual Total Time': 2.448,
			'Actual Rows': 1,
			'Actual Loops': 1,
			Output: [
				's.pid',
				's_1.ssl',
				'd.datname',
				'u.rolname',
				's.application_name',
				's.client_addr',
				's.query',
				's.query_start',
				's.state',
				's.backend_start'
			],
			'Sort Key': ['s.pid'],
			'Sort Method': 'quicksort',
			'Sort Space Used': 25,
			'Sort Space Type': 'Memory',
			'Shared Hit Blocks': 25,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 14,
			'Temp Written Blocks': 14,
			'WAL Records': 0,
			'WAL FPI': 0,
			'WAL Bytes': 0,
			Plans: [
				{
					'Node Type': 'Hash Join',
					'Parent Relationship': 'Outer',
					'Parallel Aware': false,
					'Async Capable': false,
					'Join Type': 'Left',
					'Startup Cost': 19.86,
					'Total Cost': 21.48,
					'Plan Rows': 16,
					'Plan Width': 277,
					'Actual Startup Time': 2.427,
					'Actual Total Time': 2.431,
					'Actual Rows': 1,
					'Actual Loops': 1,
					Output: [
						's.pid',
						's_1.ssl',
						'd.datname',
						'u.rolname',
						's.application_name',
						's.client_addr',
						's.query',
						's.query_start',
						's.state',
						's.backend_start'
					],
					'Inner Unique': true,
					'Hash Cond': '(s.usesysid = u.oid)',
					'Shared Hit Blocks': 22,
					'Shared Read Blocks': 0,
					'Shared Dirtied Blocks': 0,
					'Shared Written Blocks': 0,
					'Local Hit Blocks': 0,
					'Local Read Blocks': 0,
					'Local Dirtied Blocks': 0,
					'Local Written Blocks': 0,
					'Temp Read Blocks': 14,
					'Temp Written Blocks': 14,
					'WAL Records': 0,
					'WAL FPI': 0,
					'WAL Bytes': 0,
					Plans: [
						{
							'Node Type': 'Hash Join',
							'Parent Relationship': 'Outer',
							'Parallel Aware': false,
							'Async Capable': false,
							'Join Type': 'Left',
							'Startup Cost': 18.5,
							'Total Cost': 20.08,
							'Plan Rows': 16,
							'Plan Width': 217,
							'Actual Startup Time': 2.389,
							'Actual Total Time': 2.392,
							'Actual Rows': 1,
							'Actual Loops': 1,
							Output: [
								's.pid',
								's.application_name',
								's.client_addr',
								's.query',
								's.query_start',
								's.state',
								's.backend_start',
								's.usesysid',
								'd.datname',
								's_1.ssl'
							],
							'Inner Unique': true,
							'Hash Cond': '(s.datid = d.oid)',
							'Shared Hit Blocks': 21,
							'Shared Read Blocks': 0,
							'Shared Dirtied Blocks': 0,
							'Shared Written Blocks': 0,
							'Local Hit Blocks': 0,
							'Local Read Blocks': 0,
							'Local Dirtied Blocks': 0,
							'Local Written Blocks': 0,
							'Temp Read Blocks': 14,
							'Temp Written Blocks': 14,
							'WAL Records': 0,
							'WAL FPI': 0,
							'WAL Bytes': 0,
							Plans: [
								{
									'Node Type': 'Hash Join',
									'Parent Relationship': 'Outer',
									'Parallel Aware': false,
									'Async Capable': false,
									'Join Type': 'Inner',
									'Startup Cost': 17.46,
									'Total Cost': 18.99,
									'Plan Rows': 16,
									'Plan Width': 157,
									'Actual Startup Time': 2.338,
									'Actual Total Time': 2.341,
									'Actual Rows': 1,
									'Actual Loops': 1,
									Output: [
										's.pid',
										's.application_name',
										's.client_addr',
										's.query',
										's.query_start',
										's.state',
										's.backend_start',
										's.datid',
										's.usesysid',
										's_1.ssl'
									],
									'Inner Unique': false,
									'Hash Cond': '(s_1.pid = s.pid)',
									'Shared Hit Blocks': 20,
									'Shared Read Blocks': 0,
									'Shared Dirtied Blocks': 0,
									'Shared Written Blocks': 0,
									'Local Hit Blocks': 0,
									'Local Read Blocks': 0,
									'Local Dirtied Blocks': 0,
									'Local Written Blocks': 0,
									'Temp Read Blocks': 14,
									'Temp Written Blocks': 14,
									'WAL Records': 0,
									'WAL FPI': 0,
									'WAL Bytes': 0,
									Plans: [
										{
											'Node Type': 'Function Scan',
											'Parent Relationship': 'Outer',
											'Parallel Aware': false,
											'Async Capable': false,
											'Function Name': 'pg_stat_get_activity',
											Schema: 'pg_catalog',
											Alias: 's_1',
											'Startup Cost': 0,
											'Total Cost': 1,
											'Plan Rows': 100,
											'Plan Width': 5,
											'Actual Startup Time': 0.177,
											'Actual Total Time': 0.182,
											'Actual Rows': 5,
											'Actual Loops': 1,
											Output: [
												's_1.datid',
												's_1.pid',
												's_1.usesysid',
												's_1.application_name',
												's_1.state',
												's_1.query',
												's_1.wait_event_type',
												's_1.wait_event',
												's_1.xact_start',
												's_1.query_start',
												's_1.backend_start',
												's_1.state_change',
												's_1.client_addr',
												's_1.client_hostname',
												's_1.client_port',
												's_1.backend_xid',
												's_1.backend_xmin',
												's_1.backend_type',
												's_1.ssl',
												's_1.sslversion',
												's_1.sslcipher',
												's_1.sslbits',
												's_1.ssl_client_dn',
												's_1.ssl_client_serial',
												's_1.ssl_issuer_dn',
												's_1.gss_auth',
												's_1.gss_princ',
												's_1.gss_enc',
												's_1.gss_delegation',
												's_1.leader_pid',
												's_1.query_id'
											],
											'Function Call': 'pg_stat_get_activity(NULL::integer)',
											Filter: '(s_1.client_port IS NOT NULL)',
											'Rows Removed by Filter': 8,
											'Shared Hit Blocks': 20,
											'Shared Read Blocks': 0,
											'Shared Dirtied Blocks': 0,
											'Shared Written Blocks': 0,
											'Local Hit Blocks': 0,
											'Local Read Blocks': 0,
											'Local Dirtied Blocks': 0,
											'Local Written Blocks': 0,
											'Temp Read Blocks': 0,
											'Temp Written Blocks': 0,
											'WAL Records': 0,
											'WAL FPI': 0,
											'WAL Bytes': 0
										},
										{
											'Node Type': 'Hash',
											'Parent Relationship': 'Inner',
											'Parallel Aware': false,
											'Async Capable': false,
											'Startup Cost': 17.25,
											'Total Cost': 17.25,
											'Plan Rows': 16,
											'Plan Width': 156,
											'Actual Startup Time': 2.142,
											'Actual Total Time': 2.143,
											'Actual Rows': 1,
											'Actual Loops': 1,
											Output: [
												's.pid',
												's.application_name',
												's.client_addr',
												's.query',
												's.query_start',
												's.state',
												's.backend_start',
												's.datid',
												's.usesysid'
											],
											'Hash Buckets': 1024,
											'Original Hash Buckets': 1024,
											'Hash Batches': 1,
											'Original Hash Batches': 1,
											'Peak Memory Usage': 9,
											'Shared Hit Blocks': 0,
											'Shared Read Blocks': 0,
											'Shared Dirtied Blocks': 0,
											'Shared Written Blocks': 0,
											'Local Hit Blocks': 0,
											'Local Read Blocks': 0,
											'Local Dirtied Blocks': 0,
											'Local Written Blocks': 0,
											'Temp Read Blocks': 14,
											'Temp Written Blocks': 14,
											'WAL Records': 0,
											'WAL FPI': 0,
											'WAL Bytes': 0,
											Plans: [
												{
													'Node Type': 'Function Scan',
													'Parent Relationship': 'Outer',
													'Parallel Aware': false,
													'Async Capable': false,
													'Function Name': 'pg_stat_get_activity',
													Schema: 'pg_catalog',
													Alias: 's',
													'Startup Cost': 15,
													'Total Cost': 17.25,
													'Plan Rows': 16,
													'Plan Width': 156,
													'Actual Startup Time': 2.136,
													'Actual Total Time': 2.137,
													'Actual Rows': 1,
													'Actual Loops': 1,
													Output: [
														's.pid',
														's.application_name',
														's.client_addr',
														's.query',
														's.query_start',
														's.state',
														's.backend_start',
														's.datid',
														's.usesysid'
													],
													'Function Call': 'pg_stat_get_activity(NULL::integer)',
													Filter:
														"((s.state <> 'idle'::text) AND (NOT (ANY (s.state = (hashed SubPlan 1).col1))) AND (s.query_start < (now() - '00:00:05'::interval)))",
													'Rows Removed by Filter': 12,
													'Shared Hit Blocks': 0,
													'Shared Read Blocks': 0,
													'Shared Dirtied Blocks': 0,
													'Shared Written Blocks': 0,
													'Local Hit Blocks': 0,
													'Local Read Blocks': 0,
													'Local Dirtied Blocks': 0,
													'Local Written Blocks': 0,
													'Temp Read Blocks': 14,
													'Temp Written Blocks': 14,
													'WAL Records': 0,
													'WAL FPI': 0,
													'WAL Bytes': 0,
													Plans: [
														{
															'Node Type': 'Function Scan',
															'Parent Relationship': 'SubPlan',
															'Subplan Name': 'SubPlan 1',
															'Parallel Aware': false,
															'Async Capable': false,
															'Function Name': 'pg_show_all_settings',
															Schema: 'pg_catalog',
															Alias: 'a',
															'Startup Cost': 0,
															'Total Cost': 12.5,
															'Plan Rows': 1000,
															'Plan Width': 32,
															'Actual Startup Time': 1.232,
															'Actual Total Time': 1.933,
															'Actual Rows': 387,
															'Actual Loops': 1,
															Output: ['a.name'],
															'Function Call': 'pg_show_all_settings()',
															Filter: "(a.name ~~* '%a%'::text)",
															'Rows Removed by Filter': 90,
															'Shared Hit Blocks': 0,
															'Shared Read Blocks': 0,
															'Shared Dirtied Blocks': 0,
															'Shared Written Blocks': 0,
															'Local Hit Blocks': 0,
															'Local Read Blocks': 0,
															'Local Dirtied Blocks': 0,
															'Local Written Blocks': 0,
															'Temp Read Blocks': 14,
															'Temp Written Blocks': 14,
															'WAL Records': 0,
															'WAL FPI': 0,
															'WAL Bytes': 0
														}
													]
												}
											]
										}
									]
								},
								{
									'Node Type': 'Hash',
									'Parent Relationship': 'Inner',
									'Parallel Aware': false,
									'Async Capable': false,
									'Startup Cost': 1.02,
									'Total Cost': 1.02,
									'Plan Rows': 2,
									'Plan Width': 68,
									'Actual Startup Time': 0.034,
									'Actual Total Time': 0.035,
									'Actual Rows': 3,
									'Actual Loops': 1,
									Output: ['d.datname', 'd.oid'],
									'Hash Buckets': 1024,
									'Original Hash Buckets': 1024,
									'Hash Batches': 1,
									'Original Hash Batches': 1,
									'Peak Memory Usage': 9,
									'Shared Hit Blocks': 1,
									'Shared Read Blocks': 0,
									'Shared Dirtied Blocks': 0,
									'Shared Written Blocks': 0,
									'Local Hit Blocks': 0,
									'Local Read Blocks': 0,
									'Local Dirtied Blocks': 0,
									'Local Written Blocks': 0,
									'Temp Read Blocks': 0,
									'Temp Written Blocks': 0,
									'WAL Records': 0,
									'WAL FPI': 0,
									'WAL Bytes': 0,
									Plans: [
										{
											'Node Type': 'Seq Scan',
											'Parent Relationship': 'Outer',
											'Parallel Aware': false,
											'Async Capable': false,
											'Relation Name': 'pg_database',
											Schema: 'pg_catalog',
											Alias: 'd',
											'Startup Cost': 0,
											'Total Cost': 1.02,
											'Plan Rows': 2,
											'Plan Width': 68,
											'Actual Startup Time': 0.024,
											'Actual Total Time': 0.025,
											'Actual Rows': 3,
											'Actual Loops': 1,
											Output: ['d.datname', 'd.oid'],
											'Shared Hit Blocks': 1,
											'Shared Read Blocks': 0,
											'Shared Dirtied Blocks': 0,
											'Shared Written Blocks': 0,
											'Local Hit Blocks': 0,
											'Local Read Blocks': 0,
											'Local Dirtied Blocks': 0,
											'Local Written Blocks': 0,
											'Temp Read Blocks': 0,
											'Temp Written Blocks': 0,
											'WAL Records': 0,
											'WAL FPI': 0,
											'WAL Bytes': 0
										}
									]
								}
							]
						},
						{
							'Node Type': 'Hash',
							'Parent Relationship': 'Inner',
							'Parallel Aware': false,
							'Async Capable': false,
							'Startup Cost': 1.16,
							'Total Cost': 1.16,
							'Plan Rows': 16,
							'Plan Width': 68,
							'Actual Startup Time': 0.025,
							'Actual Total Time': 0.025,
							'Actual Rows': 34,
							'Actual Loops': 1,
							Output: ['u.rolname', 'u.oid'],
							'Hash Buckets': 1024,
							'Original Hash Buckets': 1024,
							'Hash Batches': 1,
							'Original Hash Batches': 1,
							'Peak Memory Usage': 12,
							'Shared Hit Blocks': 1,
							'Shared Read Blocks': 0,
							'Shared Dirtied Blocks': 0,
							'Shared Written Blocks': 0,
							'Local Hit Blocks': 0,
							'Local Read Blocks': 0,
							'Local Dirtied Blocks': 0,
							'Local Written Blocks': 0,
							'Temp Read Blocks': 0,
							'Temp Written Blocks': 0,
							'WAL Records': 0,
							'WAL FPI': 0,
							'WAL Bytes': 0,
							Plans: [
								{
									'Node Type': 'Seq Scan',
									'Parent Relationship': 'Outer',
									'Parallel Aware': false,
									'Async Capable': false,
									'Relation Name': 'pg_authid',
									Schema: 'pg_catalog',
									Alias: 'u',
									'Startup Cost': 0,
									'Total Cost': 1.16,
									'Plan Rows': 16,
									'Plan Width': 68,
									'Actual Startup Time': 0.011,
									'Actual Total Time': 0.015,
									'Actual Rows': 34,
									'Actual Loops': 1,
									Output: ['u.rolname', 'u.oid'],
									'Shared Hit Blocks': 1,
									'Shared Read Blocks': 0,
									'Shared Dirtied Blocks': 0,
									'Shared Written Blocks': 0,
									'Local Hit Blocks': 0,
									'Local Read Blocks': 0,
									'Local Dirtied Blocks': 0,
									'Local Written Blocks': 0,
									'Temp Read Blocks': 0,
									'Temp Written Blocks': 0,
									'WAL Records': 0,
									'WAL FPI': 0,
									'WAL Bytes': 0
								}
							]
						}
					]
				}
			]
		},
		Settings: {
			jit: 'off',
			effective_cache_size: '768MB',
			effective_io_concurrency: '200',
			max_parallel_workers: '2',
			max_parallel_workers_per_gather: '1',
			random_page_cost: '1.1',
			work_mem: '64kB',
			search_path: '"\\$user", public, extensions'
		},
		'Query Identifier': -4792486512343515000,
		Planning: {
			'Shared Hit Blocks': 169,
			'Shared Read Blocks': 0,
			'Shared Dirtied Blocks': 0,
			'Shared Written Blocks': 0,
			'Local Hit Blocks': 0,
			'Local Read Blocks': 0,
			'Local Dirtied Blocks': 0,
			'Local Written Blocks': 0,
			'Temp Read Blocks': 0,
			'Temp Written Blocks': 0,
			'Memory Used': 213,
			'Memory Allocated': 256
		},
		'Planning Time': 0.964,
		Triggers: [],
		'Execution Time': 2.752
	}
];
