const baseFields = {
	'Node Type': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description: 'The type of execution plan node (e.g., Seq Scan, Hash Join, Index Scan)',
		details:
			"In structured formats, sorted and hashed aggregates both have Node Type 'Aggregate' (distinguished by Strategy), unlike the text labels GroupAggregate/HashAggregate.",
		example: 'Seq Scan',
		requiredExplainMods: []
	},
	'Parallel Aware': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description:
			'Whether the node is running with parallel workers (actively divides work among parallel workers).',
		details: "In text it appears as a 'Parallel' prefix on the node name.",
		example: false,
		requiredExplainMods: []
	},
	Disabled: {
		sourceFunction: 'ExplainNode (plan_is_disabled)',
		appliesTo: ['All Plan Nodes'],
		description:
			'Whether this node itself was disabled by planner settings (e.g., an enable_* GUC) yet still chosen. Computed by subtracting child disabled-node counts; always emitted in structured formats, in text only when true.',
		example: false,
		requiredExplainMods: []
	},
	'Startup Cost': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description:
			'Estimated cost before the node can output its first row, in planner cost units. Suppressed with COSTS OFF (COSTS defaults to on).',
		example: 0.29,
		requiredExplainMods: []
	},
	'Total Cost': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description:
			'Estimated total cost to run the node to completion, in planner cost units. Suppressed with COSTS OFF.',
		example: 189.0,
		requiredExplainMods: []
	},
	'Plan Rows': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description:
			'Estimated number of rows output by this node per loop. Suppressed with COSTS OFF.',
		example: 9999,
		requiredExplainMods: []
	},
	'Plan Width': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description: 'Estimated average width of output rows, in bytes. Suppressed with COSTS OFF.',
		example: 22,
		requiredExplainMods: []
	},
	'WAL Records': {
		sourceFunction: 'show_wal_usage',
		appliesTo: ['All Plan Nodes'],
		description:
			'Number of WAL records generated by this node. WAL usage is per-node only; it is not included in the Planning section.',
		example: 0,
		requiredExplainMods: ['ANALYZE', 'WAL']
	},
	'WAL FPI': {
		sourceFunction: 'show_wal_usage',
		appliesTo: ['All Plan Nodes'],
		description: 'Number of full page images written to WAL.',
		example: 0,
		requiredExplainMods: ['ANALYZE', 'WAL']
	},
	'WAL Bytes': {
		sourceFunction: 'show_wal_usage',
		appliesTo: ['All Plan Nodes'],
		description: 'Total WAL volume generated, in bytes.',
		example: 0,
		requiredExplainMods: ['ANALYZE', 'WAL']
	},
	'WAL Buffers Full': {
		sourceFunction: 'show_wal_usage',
		appliesTo: ['All Plan Nodes'],
		description: 'PG18+: number of times WAL buffers filled, forcing a write.',
		example: 0,
		requiredExplainMods: ['ANALYZE', 'WAL']
	},
	'WAL FPI Bytes': {
		sourceFunction: 'show_wal_usage',
		appliesTo: ['All Plan Nodes'],
		description: 'Master/PG19+: total bytes of full page images written to WAL.',
		example: 0,
		requiredExplainMods: ['ANALYZE', 'WAL']
	},
	'Async Capable': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description:
			'Whether the node supports asynchronous execution (currently Foreign Scans under Append). Always emitted in structured formats.',
		example: false,
		requiredExplainMods: []
	}
};

const baseVerboseFields = {
	Output: {
		sourceFunction: 'show_plan_tlist',
		appliesTo: ['All Plan Nodes'],
		description:
			'List of target constants, function expressions, and columns returned by this node.',
		example: "['id', '1', 'now()']",
		requiredExplainMods: ['VERBOSE']
	}
};

const baseAnalyzeFields = {
	'Actual Startup Time': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description:
			'Actual time in milliseconds before the first row was returned. Requires node-level timing (TIMING, on by default with ANALYZE); omitted with TIMING OFF.',
		example: 0.096,
		requiredExplainMods: ['ANALYZE']
	},
	'Actual Total Time': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description:
			'Actual total time in milliseconds for this node, averaged per loop. Requires TIMING (on by default with ANALYZE); omitted with TIMING OFF.',
		example: 0.097,
		requiredExplainMods: ['ANALYZE']
	},
	'Actual Rows': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description: 'Actual number of rows returned per loop of this node, averaged per loop.',
		example: 1.0,
		requiredExplainMods: ['ANALYZE']
	},
	'Actual Loops': {
		sourceFunction: 'ExplainNode',
		appliesTo: ['All Plan Nodes'],
		description: 'Number of times this plan node was executed by a loop.',
		example: 1,
		requiredExplainMods: ['ANALYZE']
	}
};

// buffers is automatically enabled when ANAZLYZE is used
const baseBufferFieldsShared = {
	'Shared Hit Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description:
			'Shared buffer pages found already in the buffer pool. Node-level values need ANALYZE; planning-phase values need only BUFFERS. Since PG18, BUFFERS defaults to ON with ANALYZE.',
		detail:
			'When loops are involved, it can double count specific pages. It should dismiss the hit rate for loops and solely focus on the miss rate',
		example: 3,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Shared Read Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Shared buffer pages read in from disk.',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Shared Dirtied Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Shared buffer pages written to by the node.',
		detail:
			'Pages are usually dirtied by DML commands, INSERT, UPDATE, DELETE, and MERGE. However, SELECT commands may also alter pages. Specifically, if they come across a row that has been modified recently, they will update a hint bit, so future operations avoid checking more expensive data structures for commitment status.',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Shared Written Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Shared buffer pages that were cache evicted by this node.',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	}
};

const baseBufferFieldLocal = {
	'Local Hit Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description:
			'Total (loops and children) local (temporary-table/indexes) buffer pages found in local buffers.',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Local Read Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description:
			'Total (loops and children) local buffer pages read from disk. Applies to temp tables and indexes',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Local Dirtied Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Total (loops and children) local buffer pages altered by the node.',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Local Written Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Local buffer pages evicted from memory, most likely written to disk.',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	}
};

const baseBufferFieldTemp = {
	'Temp Read Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description:
			'Temp-files of 8kB blocks read (sort/hash spill files). Stored base/pgsql_tmp. Signs that work_mem is low ',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Temp Written Blocks': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Temp-file blocks written.',
		example: 0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	}
};

const IO = {
	'Shared I/O Read Time': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description:
			'Total time in milliseconds (includes indexes and children) spent reading pages from the OS or disk into shared buffers. Requires track_io_timing = on in addition to BUFFERS; zero/absent otherwise.',
		example: 0.0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Shared I/O Write Time': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Milliseconds spent writing shared blocks. Requires track_io_timing.',
		details:
			"it's not yet clear to me if this includes both dirtied and evicted pages or even includes WAL, too",
		example: 0.0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Local I/O Read Time': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Milliseconds spent reading local blocks. Requires track_io_timing.',
		example: 0.0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Local I/O Write Time': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Milliseconds spent writing local blocks. Requires track_io_timing.',
		example: 0.0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Temp I/O Read Time': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Milliseconds spent reading temp files. Requires track_io_timing.',
		example: 0.0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	},
	'Temp I/O Write Time': {
		sourceFunction: 'show_buffer_usage',
		appliesTo: ['All Plan Nodes', 'Planning', 'Serialization'],
		description: 'Milliseconds spent writing temp files. Requires track_io_timing.',
		example: 0.0,
		requiredExplainMods: ['BUFFERS', 'ANALYZE']
	}
};
