const fieldToNodesMap = {
	// --- Relation identification ---
	'Relation Name': [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Heap Scan',
		'TID Scan',
		'Range TID Scan',
		'Sample Scan',
		'Foreign Scan',
		'Custom Scan',
		'Parallel Seq Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan',
		'Delete',
		'Insert',
		'Update',
		'Merge'
	],
	Schema: [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Heap Scan',
		'TID Scan',
		'Range TID Scan',
		'Sample Scan',
		'Foreign Scan',
		'Custom Scan',
		'Parallel Seq Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan',
		'Delete',
		'Insert',
		'Update',
		'Merge'
	],
	Alias: [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Heap Scan',
		'TID Scan',
		'Range TID Scan',
		'Sample Scan',
		'Foreign Scan',
		'Custom Scan',
		'Parallel Seq Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan',
		'Delete',
		'Insert',
		'Update',
		'Merge',
		'Function Scan',
		'CTE Scan',
		'Subquery Scan',
		'Values Scan',
		'WorkTable Scan',
		'Named Tuplestore Scan'
	],

	// --- Optimizer / execution meta ---
	Disabled: [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Index Scan',
		'BitmapOr',
		'BitmapAnd',
		'Bitmap Heap Scan',
		'Result',
		'Foreign Scan',
		'Custom Scan',
		'Function Scan',
		'ProjectSet',
		'Values Scan',
		'CTE Scan',
		'Subquery Scan',
		'TID Scan',
		'Range TID Scan',
		'WorkTable Scan',
		'Table Function Scan',
		'Sample Scan',
		'Named Tuplestore Scan',
		'Nested Loop',
		'Nested Loop Left Join',
		'Nested Loop Right Join',
		'Nested Loop Full Join',
		'Hash Join',
		'Hash Left Join',
		'Hash Right Join',
		'Hash Full Join',
		'Merge Join',
		'Merge Left Join',
		'Merge Right Join',
		'Merge Full Join',
		'Nested Loop Semi Join',
		'Hash Semi Join',
		'Merge Semi Join',
		'Nested Loop Anti Join',
		'Hash Anti Join',
		'Merge Anti Join',
		'HashSetOp',
		'SetOp',
		'Parallel Seq Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan',
		'Parallel Append',
		'Parallel Hash',
		'Parallel Hash Join',
		'Gather',
		'Gather Merge',
		'Append',
		'Merge Append',
		'Recursive Union',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate',
		'WindowAgg',
		'Delete',
		'Insert',
		'Update',
		'Merge',
		'Hash',
		'Sort',
		'Incremental Sort',
		'Memoize',
		'Materialize',
		'Group',
		'Unique',
		'LockRows',
		'Limit'
	],
	Filter: [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Heap Scan',
		'Foreign Scan',
		'Custom Scan',
		'Function Scan',
		'TID Scan',
		'Range TID Scan',
		'WorkTable Scan',
		'Sample Scan',
		'Subquery Scan',
		'Named Tuplestore Scan',
		'Parallel Seq Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate'
	],
	'Rows Removed by Filter': [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Heap Scan',
		'Foreign Scan',
		'Custom Scan',
		'Function Scan',
		'TID Scan',
		'Range TID Scan',
		'WorkTable Scan',
		'Sample Scan',
		'Subquery Scan',
		'Named Tuplestore Scan',
		'Parallel Seq Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate'
	],

	// --- I/O timing (require BUFFERS + track_io_timing) ---
	'Shared I/O Read Time': [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Index Scan',
		'BitmapOr',
		'BitmapAnd',
		'Bitmap Heap Scan',
		'Result',
		'Foreign Scan',
		'Custom Scan',
		'Function Scan',
		'ProjectSet',
		'Values Scan',
		'CTE Scan',
		'Subquery Scan',
		'TID Scan',
		'Range TID Scan',
		'WorkTable Scan',
		'Table Function Scan',
		'Sample Scan',
		'Named Tuplestore Scan',
		'Nested Loop',
		'Hash Join',
		'Merge Join',
		'HashSetOp',
		'SetOp',
		'Parallel Seq Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan',
		'Gather',
		'Gather Merge',
		'Append',
		'Merge Append',
		'Recursive Union',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate',
		'WindowAgg',
		'Delete',
		'Insert',
		'Update',
		'Merge',
		'Hash',
		'Sort',
		'Incremental Sort',
		'Memoize',
		'Materialize',
		'Group',
		'Unique',
		'LockRows',
		'Limit'
	],
	'Shared I/O Write Time': [
		'Seq Scan',
		'Index Scan',
		'Index Only Scan',
		'Bitmap Heap Scan',
		'Foreign Scan',
		'Custom Scan',
		'CTE Scan',
		'Subquery Scan',
		'Sample Scan',
		'Nested Loop',
		'Hash Join',
		'Merge Join',
		'Gather',
		'Gather Merge',
		'Append',
		'Merge Append',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate',
		'WindowAgg',
		'Delete',
		'Insert',
		'Update',
		'Merge',
		'Hash',
		'Sort',
		'Incremental Sort',
		'Memoize',
		'Materialize'
	],
	'Local I/O Read Time': [
		'CTE Scan',
		'WorkTable Scan',
		'Named Tuplestore Scan',
		'Hash',
		'Sort',
		'Incremental Sort',
		'Memoize',
		'Materialize',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate'
	],
	'Local I/O Write Time': [
		'CTE Scan',
		'WorkTable Scan',
		'Named Tuplestore Scan',
		'Hash',
		'Sort',
		'Incremental Sort',
		'Memoize',
		'Materialize',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate'
	],
	'Temp I/O Read Time': [
		'Hash',
		'Sort',
		'Incremental Sort',
		'Memoize',
		'Materialize',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate',
		'HashSetOp',
		'SetOp'
	],
	'Temp I/O Write Time': [
		'Hash',
		'Sort',
		'Incremental Sort',
		'Memoize',
		'Materialize',
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate',
		'HashSetOp',
		'SetOp'
	],

	// --- Parallel / workers ---
	Workers: ['Gather', 'Gather Merge'],
	'Workers Planned': ['Gather', 'Gather Merge'],
	'Workers Launched': ['Gather', 'Gather Merge'],
	'Single Copy': ['Gather'],

	// --- Aggregate fields ---
	Strategy: [
		'Aggregate',
		'HashAggregate',
		'GroupAggregate',
		'MixedAggregate',
		'SetOp',
		'HashSetOp'
	],
	'Partial Mode': ['Aggregate', 'HashAggregate', 'GroupAggregate', 'MixedAggregate'],
	'Grouping Sets': ['Aggregate', 'MixedAggregate'],
	'Group Keys': ['Aggregate', 'HashAggregate', 'GroupAggregate', 'MixedAggregate'],
	'Group Key': ['Group'],
	'Hash Keys': ['Aggregate', 'HashAggregate', 'MixedAggregate'],
	'Planned Partitions': ['Aggregate', 'HashAggregate'],
	'HashAgg Batches': ['Aggregate', 'HashAggregate'],
	'Peak Memory Usage': ['Aggregate', 'HashAggregate', 'Hash', 'Parallel Hash', 'Memoize'],
	'Disk Usage': ['Aggregate', 'HashAggregate'],

	// --- Scan-specific fields ---
	'Scan Direction': [
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward'
	],
	'Index Name': [
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Index Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan'
	],
	'Index Cond': [
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Index Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan'
	],
	'Rows Removed by Index Recheck': [
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Heap Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan',
		'Parallel Bitmap Heap Scan'
	],
	'Index Searches': [
		'Index Scan',
		'Index Only Scan',
		'Index Scan Backward',
		'Index Only Scan Backward',
		'Bitmap Index Scan',
		'Parallel Index Scan',
		'Parallel Index Only Scan'
	],
	'Heap Fetches': ['Index Only Scan', 'Index Only Scan Backward', 'Parallel Index Only Scan'],
	'Recheck Cond': ['Bitmap Heap Scan', 'Parallel Bitmap Heap Scan'],
	'Exact Heap Blocks': ['Bitmap Heap Scan', 'Parallel Bitmap Heap Scan'],
	'Lossy Heap Blocks': ['Bitmap Heap Scan', 'Parallel Bitmap Heap Scan'],
	'TID Cond': ['TID Scan', 'Range TID Scan'],
	Operation: ['Foreign Scan', 'Delete', 'Insert', 'Update', 'Merge'],
	'Async Capable': ['Foreign Scan'],
	'Remote SQL': ['Foreign Scan'],
	'Foreign File': ['Foreign Scan'],
	'Foreign File Size': ['Foreign Scan'],
	'Custom Plan Provider': ['Custom Scan'],
	'Function Name': ['Function Scan'],
	'Function Call': ['Function Scan'],
	'CTE Name': ['CTE Scan', 'WorkTable Scan'],
	Storage: ['CTE Scan', 'Materialize', 'WindowAgg'],
	'Maximum Storage': ['CTE Scan', 'Materialize', 'WindowAgg'],

	// --- Join fields ---
	'Join Type': [
		'Nested Loop',
		'Nested Loop Left Join',
		'Nested Loop Right Join',
		'Nested Loop Full Join',
		'Hash Join',
		'Hash Left Join',
		'Hash Right Join',
		'Hash Full Join',
		'Merge Join',
		'Merge Left Join',
		'Merge Right Join',
		'Merge Full Join',
		'Nested Loop Semi Join',
		'Hash Semi Join',
		'Merge Semi Join',
		'Nested Loop Anti Join',
		'Hash Anti Join',
		'Merge Anti Join',
		'Parallel Hash Join'
	],
	'Inner Unique': [
		'Nested Loop',
		'Nested Loop Left Join',
		'Nested Loop Right Join',
		'Nested Loop Full Join',
		'Hash Join',
		'Hash Left Join',
		'Hash Right Join',
		'Hash Full Join',
		'Merge Join',
		'Merge Left Join',
		'Merge Right Join',
		'Merge Full Join',
		'Nested Loop Semi Join',
		'Hash Semi Join',
		'Merge Semi Join',
		'Nested Loop Anti Join',
		'Hash Anti Join',
		'Merge Anti Join',
		'Parallel Hash Join'
	],
	'Hash Cond': [
		'Hash Join',
		'Hash Left Join',
		'Hash Right Join',
		'Hash Full Join',
		'Hash Semi Join',
		'Hash Anti Join',
		'Parallel Hash Join'
	],
	'Merge Cond': [
		'Merge Join',
		'Merge Left Join',
		'Merge Right Join',
		'Merge Full Join',
		'Merge Semi Join',
		'Merge Anti Join'
	],
	'Join Filter': [
		'Nested Loop',
		'Nested Loop Left Join',
		'Nested Loop Right Join',
		'Nested Loop Full Join',
		'Hash Join',
		'Hash Left Join',
		'Hash Right Join',
		'Hash Full Join',
		'Merge Join',
		'Merge Left Join',
		'Merge Right Join',
		'Merge Full Join',
		'Nested Loop Semi Join',
		'Hash Semi Join',
		'Merge Semi Join',
		'Nested Loop Anti Join',
		'Hash Anti Join',
		'Merge Anti Join',
		'Parallel Hash Join'
	],
	'Rows Removed by Join Filter': [
		'Nested Loop',
		'Nested Loop Left Join',
		'Nested Loop Right Join',
		'Nested Loop Full Join',
		'Hash Join',
		'Hash Left Join',
		'Hash Right Join',
		'Hash Full Join',
		'Merge Join',
		'Merge Left Join',
		'Merge Right Join',
		'Merge Full Join',
		'Nested Loop Semi Join',
		'Hash Semi Join',
		'Merge Semi Join',
		'Nested Loop Anti Join',
		'Hash Anti Join',
		'Merge Anti Join',
		'Parallel Hash Join'
	],

	// --- Hash fields ---
	'Hash Buckets': ['Hash', 'Parallel Hash'],
	'Original Hash Buckets': ['Hash', 'Parallel Hash'],
	'Hash Batches': ['Hash', 'Parallel Hash'],
	'Original Hash Batches': ['Hash', 'Parallel Hash'],

	// --- Set operation fields ---
	Command: ['SetOp', 'HashSetOp'],

	// --- Sorting fields ---
	'Sort Key': ['Sort', 'Incremental Sort', 'Merge Append'],
	'Sort Method': ['Sort', 'Incremental Sort'],
	'Sort Space Used': ['Sort', 'Incremental Sort'],
	'Sort Space Type': ['Sort', 'Incremental Sort'],
	'Presorted Key': ['Incremental Sort'],
	'Full-Sort Groups': ['Incremental Sort'],

	// --- Append / partitioning fields ---
	'Subplans Removed': ['Append', 'Merge Append'],

	// --- Caching fields (Memoize) ---
	'Cache Key': ['Memoize'],
	'Cache Mode': ['Memoize'],
	'Cache Hits': ['Memoize'],
	'Cache Misses': ['Memoize'],
	'Cache Evictions': ['Memoize'],
	'Cache Overflows': ['Memoize'],

	// --- Window function fields ---
	Window: ['WindowAgg'],
	'Run Condition': ['WindowAgg'],

	// --- Data modification fields ---
	'Tuples Inserted': ['Insert', 'Update', 'Merge'],
	'Tuples Updated': ['Update', 'Merge'],
	'Tuples Deleted': ['Delete', 'Merge'],
	'Tuples Skipped': ['Insert', 'Update', 'Delete', 'Merge'],
	'WAL Records': ['Insert', 'Update', 'Delete', 'Merge'],
	'WAL Bytes': ['Insert', 'Update', 'Delete', 'Merge'],
	'WAL FPI': ['Insert', 'Update', 'Delete', 'Merge'],
	'Trigger Information': ['Insert', 'Update', 'Delete', 'Merge'],

	// --- Misc fields ---
	'One-Time Filter': ['Result']
};
